# Your Wi-Fi's SSID and password
wifi_ssid: <redacted>
wifi_password: <redacted>

ssid1_pswd: <redacted>
ssid1_name: <redacted>

ssid2_pswd: <redacted>
ssid2_name: <redacted>

ssid3_pswd: <redacted>
ssid3_name: <redacted>

# Your domain
domain: .local

# Passwords for appl, ota and homeassistant
app_pswd: <redacted>
ota_pswd: <redacted>
ha_pswd: <redacted>

# UDP server wmbusmeter
wmbus_server:  <redacted>
wmbus_server_port: 7337

# Backup
web_username: <redacted>
web_password: <redacted>

# Watermeter ID, only HEX is working for me
watermeterId: 0x43430778
watermeterIx: 18444343

# Using wmbusmeters i a pipe
watermeterhost: <redacted>
wmbusmeter_host: <redacted>

# service target
service_host: <redacted>
data_host: <redacted>

# syslog
syslog_server: <redacted>
syslog_port: <redacted>

## webserver 3.0 change url to your webserver
webserver_jsurl:  "https://raw.githubusercontent.com/zibous/ha-watermeter/b0e3ed3f9b7c9f8da74bfe37389cee26ec8358e3/esphome/webserver/v3/www.js"
webserver_cssurl: "https://raw.githubusercontent.com/zibous/ha-watermeter/b0e3ed3f9b7c9f8da74bfe37389cee26ec8358e3/esphome/webserver/v3/webserver.css"