# Your Wi-Fi's SSID and password
wifi_ssid: <redacted>
wifi_password: <redacted>

ssid1_pswd: <redacted>
ssid1_name: <redacted>

ssid2_pswd: <redacted>
ssid2_name: <redacted>

# Your domain
domain: <redacted>

# Passwords for appl, ota and homeassistant
app_pswd: <redacted>
ota_pswd: <redacted>
ha_pswd: <redacted>

# Your watermeter
watermeterId: <redacted>
watermeterhost: <redacted>

# UDP server wmbusmeter
wmbus_server:  <redacted>
wmbus_server_port: 7337

# Backup
web_username: <redacted>
web_password: <redacted>