# Your Wi-Fi SSID and password
wifi_ssid: <redacted>
wifi_password: <redacted>

ssid1_pswd: <redacted>
ssid1_name: <redacted>

ssid2_pswd: <redacted>
ssid2_name: <redacted>

domain: <redacted>

app_pswd: <redacted>
ota_pswd: <redacted>
ha_pswd: <redacted>

watermeterId: <redacted>
watermeterhost: <redacted>